services:
  - type: web
    name: sua-agenda-flask
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 2 --threads 2 --timeout 120 --keep-alive 2
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: GUNICORN_WORKERS
        value: 2
      - key: GUNICORN_THREADS
        value: 2
      - key: GUNICORN_TIMEOUT
        value: 120
      - key: LOG_LEVEL
        value: INFO
    disk:
      name: flask-uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
